# width shift applied

In [2]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(width_shift_range=[-10,10])
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)

(48, 48)


In [3]:
data=np.load('data.npy')
data

array([['okey', '128', '128', ..., '127', '99', '49'],
       ['okey', '66', '69', ..., '82', '82', '82'],
       ['okey', '66', '69', ..., '82', '82', '82'],
       ...,
       ['okey', '118', '120', ..., '26', '26', '26'],
       ['okey', '118', '120', ..., '26', '26', '26'],
       ['okey', '118', '120', ..., '26', '26', '26']], dtype='<U4')

In [4]:
X = data[:,1:].astype(int)
y = data[:,0]
print(X.shape)
print(y)

(1860, 2304)
['okey' 'okey' 'okey' ... 'okey' 'okey' 'okey']


In [5]:
from matplotlib import pyplot
data = np.load('data.npy')
X = data[:,1:].astype(int)
y = data[:,0]
image=X[1452]
resizeimage = np.resize(image,(48,48))
print(resizeimage)

[[111 112 113 ...  21  21  21]
 [111 112 114 ...  52  52  52]
 [110 111 114 ...  45  45  45]
 ...
 [102  50  70 ...  69  69  69]
 [ 82  80  68 ...  67  67  67]
 [ 81  72  51 ...  62  62  62]]


# Height shift applied

In [6]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(height_shift_range=0.3)
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(3720, 2305)


# Horizontal flip applied

In [9]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(horizontal_flip=True)
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(5580, 2305)


# Vertical flip applied

In [10]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(vertical_flip=True)
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(7440, 2305)


# Random Rotation applied

In [11]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(rotation_range=180)
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(9300, 2305)


# Random brightness applied

In [12]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(brightness_range=[0.1,1.0])
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(11160, 2305)


# Random Zoom applied

In [13]:
import numpy as np
import cv2
import os
import dlib
import matplotlib.pyplot as plt
frames = []
output = []
for i in range(1,94):
    filename='../Images/okey/okey ('+str(i)+').jpg'
    img = load_img(filename)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(zoom_range=[0.3,1])
    it = datagen.flow(samples, batch_size=1)
    for i in range(20):
        batch = it.next()
        image = batch[0].astype('uint8')
        #image_shape=image.shape
        gray_image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
        image_shape=gray_image.shape
        frames.append(gray_image.flatten())
        output.append(['okey'])
X = np.array(frames)
y = np.array(output)

data = np.hstack([y, X])

f_name = "data.npy"

if os.path.exists(f_name):
    old = np.load(f_name)
    data = np.vstack([old, data])

np.save(f_name, data)
print(image_shape)
print(data.shape)

(48, 48)
(13020, 2305)


# so we have 13020 okey images in 48X48 form 